name: rivoj_uz_project
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
     - assets/icons/


  fonts:
     - family: Archivo
       fonts:
         - asset: assets/fonts/Archivo-Regular.ttf
         - asset: assets/fonts/Archivo-Medium.ttf
           weight: 500
         - asset: assets/fonts/Archivo-Bold.ttf
           weight: 700
         - asset: assets/fonts/Archivo-Light.ttf
           weight: 300
         - asset: assets/fonts/Archivo-SemiBold.ttf
           weight: 600
         - asset: assets/fonts/Archivo-ThinItalic.ttf
           weight: 100
           style: italic


